import type { PerfectDay } from 'chrono-pi-data';

import { iCalUid } from './uid';

// The π-encoded instant 09:26:53.589 — same constant the site counts down to
// (apps/site/src/lib/view.ts). Google Calendar ignores sub-second precision,
// so the event starts at 09:26:53 in the operator's timezone.
export const PI_INSTANT_TIME = '09:26:53';

const EVENT_MINUTES = 15;

export interface GcalEvent {
  iCalUID: string;
  summary: string;
  description: string;
  start: { dateTime: string; timeZone: string };
  end: { dateTime: string; timeZone: string };
  transparency: 'transparent';
}

function plusMinutes(time: string, minutes: number): string {
  const [h = 0, m = 0, s = 0] = time.split(':').map(Number);
  const total = h * 60 + m + minutes;
  const hh = String(Math.floor(total / 60) % 24).padStart(2, '0');
  const mm = String(total % 60).padStart(2, '0');
  const ss = String(s).padStart(2, '0');
  return `${hh}:${mm}:${ss}`;
}

// π with a decimal point restored, as far as the reading's digits go: '3141592653589' → '3.141592653589'.
function prettyDigits(digits: string): string {
  return digits.length > 1 ? `${digits[0]}.${digits.slice(1)}` : digits;
}

export function buildEvent(day: PerfectDay, timeZone: string): GcalEvent {
  return {
    iCalUID: iCalUid(day),
    summary: `π ${prettyDigits(day.digits)} — ${day.calendarId} (${day.reckoningId})`,
    description: [
      `Perfect π-day: the ${day.calendarId} calendar read as ${day.reckoningId} spells π to depth ${day.depth}.`,
      `Digits: ${prettyDigits(day.digits)}`,
      `Tier: ${day.tier}`,
      '',
      'Generated by chrono-pi sync — do not edit; re-syncs overwrite.',
    ].join('\n'),
    start: { dateTime: `${day.isoDate}T${PI_INSTANT_TIME}`, timeZone },
    end: {
      dateTime: `${day.isoDate}T${plusMinutes(PI_INSTANT_TIME, EVENT_MINUTES)}`,
      timeZone,
    },
    transparency: 'transparent',
  };
}
